### ISSUE TITLE
Tracking testing results for Files Primary S3 1.1.2

### ISSUE THREAD

**Issue by davitol** [owncloud/files_primary_s3#339]
| Test Case                                | Expected Result                          | Result         | Related Comment |
| ---------------------------------------- | ---------------------------------------- | -------------- | --------------- |
| *Prerequirements: Have a primary storage configured for all files in the system (Scality or Ceph preferred, Minio is not officially supported), see https://buildmedia.readthedocs.org/media/pdf/s3-server/doc-adddoc/s3-server.pdf p.12* |                                          |                |                 |
| Create 3 users, upload several files with user1 (some in a subfolder), share some with user2, using user2 share some with user3. Using user3 download one of the files. | No problems. User3 can download the file. | ✅    |                 |
| Rename a file, in root and in a subsubfolder. | Files are renamed without problems.      | ✅ |                 |
| Connect desktop client. Sync a small file to the server of about 1MiB. Download it with web interface. | File is uploaded and downloaded correctly. | ✅|                 |
| Connect desktop client. Sync a file of ca 256MiB to the server, download it with web interface. | File is uploaded and downloaded correctly. | ✅ |                 |
| Federate share a folder and a file with another server which doesn't use objectstore. | Receiver can interact with the folder and file shared. | ✅            |                 |
| Federate share a folder and a file from another server which doesn't use objectstore with the server using objectstore. | User in objectstore server can interact with the folder shared. | ✅             |                 |
| Favorite several files and folders. Unfavorite them. Refresh page. | Files are favorited and unfavorited without problems. Check that state remains after refreshing. | ✅ |                 |
| As user1: Public share a folder and a file.        | Folder and file can be used normally by anonymous users. | ✅ |                 |
| Add comments to a shared file with several users. | No errors found.                         | ✅ |                 |
| Add comments to a shared folder with several users. | No errors found.                         | ✅|                 |
| Add tags to a shared folder with several users. | No errors found.                         | ✅ |                 |
| Search tags previously assigned.         | No errors found.                         | ✅ |                 |
| Check that activity is correctly recorded. | No errors found.                         | ✅|                 |
| Set logging level to INFO. Check that user file actions are logged by admin audit. | Actions are logged correctly.            | ✅ |                 |
| Using the URL provided by user1: 1. enter the link.(without being logged in, use a different browser or have the cache cleaned) 2. Upload an existing file. | You can choose between cancel the upload and renaming the file. |  ✅ |                 |
| **Known issues from the past**           |                                          |                |                 |
| As admin user create a user "user1" and share a folder "SHARED" with "user1". As "user1" upload some files to root folder. Favorite them, add comments and tags. Move those files into "SHARED" folder received from admin user. | FileID should be kept after moving to a shared folder as recipient. All metadata must still be there, favorites, comments and tags. | ✅|                 |
| As admin user upload a file bigger than 5GB using web ui. | File can be uploaded, finishing correctly joining the chunks without problems. | ✅|                 |
| As admin user connect desktop client and sync a file bigger than 5GB. | File can be uploaded, finishing correctly joining the chunks without problems. | ✅ |                 |
| As admin user upload a new file to the root folder. Check versions of that file. | It doesn't have any version. No version is created when uploading a new file. | ✅|           https://github.com/owncloud/files_primary_s3/issues/278 https://github.com/owncloud/files_primary_s3/issues/156 https://github.com/owncloud/files_primary_s3/issues/67      |
| As admin user create three users "user1", "user2" and "user3".  As "user1" upload a file "file.txt".  As "user1" share "file.txt" with "user3".  Run occ files:transfer-ownership user1 user2. | "user2" gets "user1"'s files, including shares."user3" can still have access to the shared file "file.txt". |✅  |                 |

**Comment by davitol** [comment]
## Changelog

- [ ] Translations https://github.com/owncloud/enterprise/issues/3838#issuecomment-598872824

**Comment by phil-davis** [comment]
PR #340 has been merged. Translations should be included in the next tarball.

**Comment by davitol** [comment]
running occ command with no parameters `occ s3:list`

![Screen Shot 2020-04-27 at 11 09 00](https://user-images.githubusercontent.com/10596560/80360291-67af7e80-887f-11ea-8797-4e268943fdad.png)
Why does it ask for the bucket cors? Should not it just list in the same way it is shown in the output of the aws-cli command shown below in the screenshot?


running it with parameters LGTM


 
![Screen Shot 2020-04-27 at 11 30 20](https://user-images.githubusercontent.com/10596560/80360351-7dbd3f00-887f-11ea-872e-3dd71a3bbd3a.png)

**Comment by davitol** [comment]
### Fixed

- [ ]  Bugfix/l10n - [#323](https://github.com/owncloud/files_primary_s3/issues/323)

### Changed

- [ ]  Update PHP dependencies - [#316](https://github.com/owncloud/files_primary_s3/issues/316)

### Added

- [ ]  Add phpdoc for Symfony Command execute - [#309](https://github.com/owncloud/files_primary_s3/issues/309)
- [ ]  Add l10n to dist/appstore build - [#340](https://github.com/owncloud/files_primary_s3/issues/340)
