### ISSUE TITLE
Primary S3 1.0.0 release checklist

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/files_primary_s3#60]
**When marking a task as done, please add your name to the task!**

### Reason

Releasing the new shiny objectstore implementation 🎆 🎉 🚀 

### QA
- [x] Create release branch
- [x] Create "$version Testplan"  https://github.com/owncloud/files_primary_s3/issues/61
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) https://github.com/owncloud/files_primary_s3/issues/61

### Marketing
- [x] Ping RocketChat channel #marketing @patrickjahns
- [x] Check/adapt info.xml stuff https://github.com/owncloud/files_primary_s3/pull/88 @pmaier1
- [x] Check/adapt screenshot @pmaier1
- [ ] Blog post or other communication if applicable

### Documentation
- [ ] Documentation required as first time release @settermjd
  - [ ] migration guide from `objectstore` to `files_primary_s3`: https://github.com/owncloud/documentation/issues/4168

### Build & Marketplace release

- [x] Bump version in info.xml
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version'
- [x] Create github tag for '$version'
- [x] Build and sign tarball from github tag '$version'
- [x] Upload to marketplace
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md
- [x] Create PR to merge changes back to `master`

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks a possibly related issue is https://github.com/owncloud/files_primary_s3/pull/35 (Ready for 10.1).

**Comment by pmaier1** [comment]
Added PR for description, etc. https://github.com/owncloud/files_primary_s3/pull/88

**Comment by pmaier1** [comment]
Please add this before release https://github.com/owncloud/files_primary_s3/pull/96

**Comment by DeepDiver1975** [comment]
> Add a new 'Unreleased' section in CHANGELOG.md

https://github.com/owncloud/files_primary_s3/pull/102

**Comment by PVince81** [comment]
Documentation ticket is here, let's follow up there: https://github.com/owncloud/documentation/issues/4168

Closing release ticket, app is out
