### ISSUE TITLE
1.0.0 Testplan

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/files_primary_s3#61]
## Automated Test Suites
- [x] unit tests  @patrickjahns
- [x] acceptance tests @patrickjahns
- [ ] automated tests for storage relevant apps @patrickjahns
  - [x] files firewall
  - [ ] workflow
  - [x] files_antivirus
  - [x] guests

## Smashbox Results
- [ ] ceph
- [ ] s3

## Manual QA Sanity Check
- [x] https://github.com/owncloud/files_primary_s3/issues/65 done by @davitol 

#### Upload large files
- [x] 6GB via sync client - verify checksum afterward
  - [x] ceph @patrickjahns
  - [x] scality @patrickjahns
- [ ] 6GB via sync client -> old style chunking
- [ ] 6GB via webui -> verify checksum afterward
- [ ] via cadaver -> verify checksum afterward

#### Handling of trashbin/version of a large file
- [ ] move shared file to trashbin and restore
  - [ ] as sharee
  - [ ] as share receiver
- [ ] upload a version of a large file and restore
- [ ] upload another version of a large file and share
  - [ ] restore a version of a large file as sharee
  - [ ] restore a version of a large file as share receiver
  
#### handling large folders
1) clone core repository - run make - sync via syncclient 
- [x] sync up via sync client @patrickjahns
- [ ] download as zipfile again @patrickjahns

share folder uploaded in 1)
- [ ] download as zip file @patrickjahns

### primarily relevant
- [x] guests (because of write only Storage wrapper) @davitol 
- [x] workflow @davitol [details](https://github.com/owncloud/files_primary_s3/issues/61#issuecomment-393211296)
- [x] files_firewall @davitol [details](https://github.com/owncloud/files_primary_s3/issues/61#issuecomment-394258603)
- [x] files_antivirus @davitol [details](https://github.com/owncloud/files_primary_s3/issues/61#issuecomment-394608063)
- ❌  gallery  https://github.com/owncloud/files_primary_s3/issues/72
- [x] comments @davitol
- [ ] config report
- [x] market @davitol
- [x] theme enterprise @davitol [details](https://github.com/owncloud/files_primary_s3/issues/61#issuecomment-393123653)
- [x] impersonate @davitol [details](https://github.com/owncloud/files_primary_s3/issues/61#issuecomment-395335697)
- ~~files_texteditor~~ -> ❌ know limitations / issues
- [x] activity @davitol [details](https://github.com/owncloud/files_primary_s3/issues/61#issuecomment-3930833060)

### Other apps 
- [ ] collabora
- [ ] only office

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @DeepDiver1975.

Possibly related issues are https://github.com/owncloud/files_primary_s3/issues/60 (1.0.0 release checklist), and https://github.com/owncloud/files_primary_s3/pull/35 (Ready for 10.1).

**Comment by patrickjahns** [comment]
## activity app
### summary
Everything tested works as expected - no strange behavior

### tests performed
- ☑️ as user bob share a file with angelica - see that bobs activity feed contains the notification

**Comment by davitol** [comment]
| Test Case                                | Expected Result                          | Result Firefox | Result Safari  |  Result Chrome | Related Comment |
| ---------------------------------------- | ---------------------------------------- | -------------- | -------------- | -------------- | -------------- | ------------- | --------------- |
| Open login page, and login.              | The theme background is shown and the user can login without problems. | :construction: | :construction: | :construction: | 🚧             | 🚧            |                 |
| The top bar appears correctly in the files and admin page. | No visualization problems.               | 🚧             | :construction: | :construction: | :construction: | 🚧            |                 |
| Menus can be opened and they are well positioned. | No visualization problems.               | 🚧             | 🚧             | 🚧             | 🚧             | 🚧            |                 |
| Make the server return an error. For example put a firewall rule about blocking access to a particular group and try to access with a member of that group. | Background image is the theme one.       | 🚧             | 🚧             | 🚧             | 🚧             | 🚧            |                 |
| Public share a link. Open it without being logged in. | The theme is the expected one.           | 🚧             | 🚧             | 🚧             | 🚧             | 🚧            |                 |

**Comment by davitol** [comment]
## 'Guest App' Test Plan

## Testing functionality

Test Case | Expected Result | Result | Related Comment
------------- | -------------- | ----- | ------
**CLI commands** |  |   |
|  |   |
Enable Guest app via CLI using ```occ app:enable guests``` | The apps is enabled | :construction:  |
Disable Guest app via CLI using ```occ app:disable guests``` | The apps is disabled | :construction:  |
**Add Guest User in sharetabview** |  |   |
|  |   |
Create a guest user via email |  | :construction:  |
Create a guest user via email sharing from another guest user |  | :construction:  |
Create a guest user via email sharing from an LDAP user |  | :construction:  |
Create a guest user via email sharing from an Shibboleth user | | :construction:  |
Try to create a guest user via email when a server email is not set or it is invalid|  An error message should be shown | :construction:  |
Try to create a guest user via email with an invalid email format | An error message should be shown | :construction:  |
Try to create a guest user via email with an already used email | An warning about a username with that email already exists should be shown | :construction:  |
Try to create a guest user via email already registered by email | A warning about the token is invalid should be shown | :construction:  |
Create a guest user via email using a password that fits password policy | Check that the user receives the email and can register into oC | :construction:  | 
Create a guest user via email using a password that doesn't fit password policy | Check that the user receives the email and cannot register into oC. A warning related to password policy should be shown | :construction:  |
**Users Menu** |  |   |
|  |   |
Delete a guest user in user's menu | The user is deleted and no longer available in oC. Check that user disappears from sharetabviews | :construction:  |
Try to create a guest user in users menu adding it to the guest_group| The user should not be created. A warning should be shown | :construction:  |
Change the guest user's password in users menu | The new password is set for the guest user | :construction:  |
**Guest User account**|  |   |
|  |   |
Log in the guest user account  | Check that the shared file/folder appears with the right permissions | :construction:  |
Reshare a folder with folder permissions to another guest user | Check that the shared folder works fine | :construction:  |
In personal page, change users email. Then as admin try to create a new guest user with the old mail  | Check that the mail which was used for the register is kept | :construction:  |
**Settings page**|  |   |
|  |   |
Change Guest Group name  | The group name for guest is changed. Check this change in Users Page and the shares are kept | :construction:  |
Set Guest Group name as empty  | A warning error should be shown and the previous name should be kept | :construction:  |
Limit guest access to an app whitelist checked, modify the list and save  | Check that only apps listed are available for guests users | :construction:  |
**WebUI and browsers**|  |   |
|  |   |
Check that guests menu in sharing section works fine using FireFox as browser |  | :construction:  |

**Comment by davitol** [comment]
## 'WorkFlow App' Test Plan

## Testing functionality

TBD

**Comment by davitol** [comment]
We need to re-test (sanity test) it later with https://github.com/owncloud/core/pull/31659 
it fixes a regression because of objectstore changes

**Comment by davitol** [comment]
## Customgroups Test Plan


| Test Case                                | Expected Result                          | Result         | Related Comment |
| ---------------------------------------- | ---------------------------------------- | -------------- | --------------- |
| Enable the app.                          | No problems found.                       | ☑️         |                 |
| Disable and enable the app using CLI.    | No problems found.                       | ☑️         |                 |
| Create a custom group.                   | Custom group is created correctly.       | ☑️        |                 |
| Create an already existing custom group. | The group cannot be created again.       | ☑️         |                 |
| Delete a custom group.                   | The group is removed correctly.          | ☑️        |                 |
| Rename a custom group.                   | The group is renamed correctly.          | ☑️         |                 |
| As a non-admin member try to rename its custom group. | He cannot rename its custom group        | :gear:         |                 |
| Get members of a group.                  | Members are retrieved correctly.         | ☑️         |                 |
| Check that the creator of a custom group becames admin automatically. | No problems found.                       | :gear:         |                 |
| As a creator of a custom group add members. | Members are added correctly.             | ☑️        |                 |
| As non-admin member of a custom group try to add members. | Non-admin member cannot add members.     | ☑️        |                 |
| As non-member of a custom group try to list its members. | Non-admin member cannot list members.    | ☑️         |                 |
| As custom group member try to list members. | Custom group member can list members.    | :gear:         |                 |
| As non-admin member of a custom group try to delete a custom group | A non-admin member of a custom group cannot delete a custom group. | ☑️         |                 |
| As a creator of a custom group try to remove members. | Creator of a custom group can remove members. | ☑️        |                 |
| As a non-admin member of a custom group try to remove members | A non-admin member of a custom group cannot remove members. | :gear:         |                 |
| Not having more admins on a custom group, as group owner try to remove yourself from the group | Group owner cannot remove self if no other admin exists in the group. | ☑️         |                 |
| As member of a custom group leave the custom group. | A member of a custom group can leave the custom group himself. | :gear:         |                 |
| As a user check the groups you belong to. | A user can list his groups.              | ☑️        |                 |
| As owner of a group, try to change the role of a member of the group. | Role is changed successfully.            | ☑️         |                 |
| Create a custom group and let user 'member1' as admin. | 'member1' is the new admin of the group. No problems. | ☑️         |                 |
| As superadmin of the server create a custom group. | Superadmin can create custom groups.     | ☑️         |                 |
| As superadmin add a user to a custom group. | Superadmin can add a user to any custom group. | ☑️         |                 |
| As superadmin rename a custom group.     | Superadmin can rename any custom group.  | :gear:         |                 |
| As superadmin change role of a member of a group making him admin. | Superadmin can change roles.             | ☑️         |                 |
| As superadmin remove a member of a custom group. | Superadmin can remove members.           | ☑️         |                 |
| As superadmin try to list members of a custom group. | Superadmin can list members.             | ☑️         |                 |
| As member converted to group owner add members to group, remove members, change roles and list members. | A member converted to group owner can do the same as group owner | ☑️         |                 |
| Having no other admin in a custom group, as group owner try to remove your own admin permissions. | A group owner cannot remove his own admin permissions if there is no other owner in the group | ☑️         |                 |
| Check that a non-existing user cannot be added to a custom group |                                          | ☑️
| **Using frontend**                       |                                          |                |                 |
| Create a custom group.                   | Custom group is created correctly.       | ☑️             |                 |
| Create an already existing custom group. | The group cannot be created again. A warning appears. | ☑️             |                 |
| Delete a custom group.                   | The group is removed correctly.          | ☑️             |                 |
| Rename a custom group.                   | The group is renamed correctly.          | ☑️             |                 |
| As a creator of a custom group add members. | Members are added correctly.             | ☑️             |                 |
| As regular user member of a custom group check the users in the custom groups. | You can see the other members.           | ☑️             |                 |
| As non-admin member of a custom group try to add members. | Non-admin member cannot add members. There is no UI element to do it. | ☑️             |                 |

**Comment by davitol** [comment]
> 6GB via webui -> verify checksum afterward

With current compose infrastructure, the port for s3 is currently not exposed. So we can consider to deploy  with the port exposed in the future if we consider it worthy (to be discussed)

**Comment by davitol** [comment]
QA was finished, let's close the ticket.
